name: Echo Command Example

on:
  push:
    branches:
      - main

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run echo command
        run: echo "hoge"

      - name: cpu command
        run: lscpu
